apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "coturn.fullname" . }}-config
  labels:
{{ include "coturn.labels" . | nindent 4}}
data:
  turnserver.conf: | {{ tpl .Values.conf . | nindent 4 }}