{{- $portRange := untilStep (int .Values.ports.from) (int (add1 .Values.ports.to)) 1 -}}
apiVersion: apps/v1
kind: {{ .Values.kind }}
metadata:
  name: {{ include "coturn.fullname" . }}
  labels:
{{ include "coturn.labels" . | indent 4 }}
spec:
  {{- if eq .Values.kind "Deployment" }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "coturn.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        # re-roll deployment on config change
        checksum/coturn-config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "coturn.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- if .Values.runAsNonRoot }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
{{- end }}
      {{- if eq .Values.kind "DaemonSet" }}
      hostNetwork: true
      {{- end }}
      containers:
        - name: "coturn"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["-c", "/turnserver.conf"]
          ports:
            - name: turn-3478
              containerPort: 3478
              protocol: UDP
          {{- range $portRange }}
            - name: turn-{{ . }}
              containerPort: {{ . }}
              {{- if eq $.Values.kind "DaemonSet" }}
              hostPort: {{ . }}
              {{- end }}
              protocol: UDP
          {{- end }}
          volumeMounts:
            - name: coturn-config
              mountPath: /turnserver.conf
              subPath: turnserver.conf
              readOnly: true
            - name: var-tmp
              mountPath: /var/tmp
{{- if .Values.runAsNonRoot }}
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
{{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: coturn-config
          configMap:
            name: {{ include "coturn.fullname" . }}-config
        - name: var-tmp
          emptyDir: {}