apiVersion: v1
entries:
  jitsi-meet:
  - apiVersion: v2
    appVersion: stable-5390-3
    created: "2021-05-27T17:45:31.76545+02:00"
    dependencies:
    - condition: prosody.enabled
      name: prosody
      repository: ""
      version: '*'
    description: A Helm chart for Kubernetes
    digest: f50c08198000e2b25b1d21fd926a7392bf3027e3e5bb984c9501744389aa90a8
    name: jitsi-meet
    type: application
    urls:
    - https://jitsi-contrib.github.io/jitsi-helm/jitsi-meet-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: stable-5390-3
    created: "2021-05-27T17:45:31.759989+02:00"
    dependencies:
    - condition: prosody.enabled
      name: prosody
      repository: ""
      version: '*'
    description: A Helm chart for Kubernetes
    digest: f5d23258f3021f42029514be9206910864123ecca5bbcc9505b0cc100e7bd5e0
    name: jitsi-meet
    type: application
    urls:
    - https://jitsi-contrib.github.io/jitsi-helm/jitsi-meet-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: stable-5390-3
    created: "2021-05-27T17:45:31.757968+02:00"
    dependencies:
    - condition: prosody.enabled
      name: prosody
      repository: ""
      version: '*'
    description: A Helm chart for Kubernetes
    digest: 3579cde89bd94faf4d94efd94524c64bebf95cfc123446dc0c535bf8e23b70fe
    name: jitsi-meet
    type: application
    urls:
    - https://jitsi-contrib.github.io/jitsi-helm/jitsi-meet-0.1.2.tgz
    version: 0.1.2
generated: "2021-05-27T17:45:31.755821+02:00"
